### PR TITLE
Features

### PR DESCRIPTION
**Pull request by calvindo95**
- added xml file endpoint
- added APM setup
- added latency test
- added response throughput test
- added request throughput test
- added data throughput test via fio
- various small fixes

### CODE REVIEW

**Review by bartell-lin — COMMENTED** [review]
For added xml commit
Looks good overall, but I see a few lines of code that you never use like ip_addr and start in the file resource. I assume that is from older code

**Review by bartell-lin — COMMENTED** [review]
latency.cpp
-for postfields, I think it is proper to use something like text/xml if you are dealing with xml files instead of gibberish
-~~I'm not sure why you are using vec.begin() + 1 in the get_average function if that is intentional~~
I see you fixed it later on

**Review by bartell-lin — COMMENTED** [review]
request.cpp
-overall good logic. It think it might be easier to send x requests and divide that by the time it took but your way works just as well

I think the story said something about checking number/ratio of successful requests if you want to log that

**Review by bartell-lin — COMMENTED** [review]
response.cpp

- Why are you calculating with header size? I think you should be using download size to get the size of the actual contents

- You are passing total_throughput by reference which is not a bad idea, an alt solution may be to create a struct to return both error code and total_throughput. This way you have the option to return more values if need be

- I think for atomic, you need to use fetch_add() instead of  += since += counts as 2 different operations

**Comment by calvindo-ss** [comment]
> request.cpp -overall good logic. It think it might be easier to send x requests and divide that by the time it took but your way works just as well
> 
> I think the story said something about checking number/ratio of successful requests if you want to log that

I wrote it so that the test would automatically end when I hit the first non 200 code. Maybe I will change it to count successful/unsuccessful requests over a period of time in the future.

**Comment by calvindo-ss** [comment]
> response.cpp
> 
> * Why are you calculating with header size? I think you should be using download size to get the size of the actual contents
> * You are passing total_throughput by reference which is not a bad idea, an alt solution may be to create a struct to return both error code and total_throughput. This way you have the option to return more values if need be
> * I think for atomic, you need to use fetch_add() instead of  += since += counts as 2 different operations

You are right about using header size. I think I got confused due to libcurl's large number of options.

For the use of structs, I purposely used atomics just to 'reinforce' my use of them even though it's not the best choice for what we're doing.

I actually didn't know that about += for atomics.

**Pull request merged**
